name: new_i3d
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas
  - blas-devel
  - brotlipy
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - freetype
  - idna
  - intel-openmp
  - jpeg
  - lcms2
  - lerc
  - libblas
  - libcblas
  - libdeflate
  - liblapack
  - liblapacke
  - libpng
  - libtiff
  - libuv
  - libwebp
  - libwebp-base
  - libxcb
  - libzlib
  - lz4-c
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gmp
  - m2w64-libwinpthread-git
  - mkl
  - mkl-devel
  - mkl-include
  - msys2-conda-epoch
  - numpy
  - openjpeg
  - openssl
  - pillow
  - pip
  - pthread-stubs
  - pycparser
  - pyopenssl
  - pysocks
  - python=3.10
  - python_abi
  - requests
  - setuptools
  - sqlite
  - tbb
  - tk
  - typing_extensions
  - tzdata
  - urllib3
  - vc
  - vs2015_runtime
  - wheel
  - win_inet_pton
  - wincertstore
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zlib
  - zstd
  - pip:
    - imageio
    - networkx
    - packaging
    - plyfile
    - pyparsing
    - pywavelets
    - scikit-image
    - scipy
    - tifffile
    - PyYAML
    - open3d
